apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-kube-app
  namespace: my-kubernetes
spec:
  replicas: 2
  template: 
    metadata:
      labels:
        app: kube-app
    spec:
      volumes:
        - name: jobapplicationname
          hostPath:
            path: ./JobApplication
            type: DirectoryOrCreate
      containers:
        - name: my-nginx-2
          image: nginx:latest
          volumeMounts:
            - mountPath: /JobApplication
              name: jobapplicationname
          ports:
            - containerPort: 80
              protocol: TCP
            
  selector:
    matchLabels:
      app: kube-app