# apiVersion: v1
# kind: Service
# metadata: 
#   name: service-kube-app
#   namespace: my-kubernetes
# spec:
#   ports:
#     - port: 80
#     - nodePort: 3000
#   selector:
#     app: kube-app


apiVersion: v1
kind: Service
metadata:
  name: service-yaml-file
  namespace: my-kubernetes
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31000
  selector: 
    app: kube-app